config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development? # rubocop:disable Style/IfUnlessModifier
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: :auth, controllers: {
        token_validations:  'api/v1/overrides/token_validations',
        registrations:      'api/v1/overrides/registrations',
        sessions:           'api/v1/overrides/sessions',
        omniauth_callbacks: 'api/v1/overrides/omniauth_callbacks',
        passwords:          'api/v1/overrides/passwords'
      }

      resources :mailing_lists, path: '', only: %i[show] do
        resources :issues, only: %i[index show]
      end

      resources :subscriptions, only: %i[create]

      resources :links, only: %i[show]

      namespace :dashboard do
        resources :mailing_lists, except: %i[edit new] do
          resources :subscriptions, only: %i[index]
        end
      end

      get :subscribe, to: 'subscriptions#update', path: 'subscriptions/subscribe'
    end
  end
end

app/models/mailing_list.rb
class MailingList < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged

  belongs_to :user
  has_many :subscriptions, dependent: :destroy
  has_many :issues, dependent: :destroy

  def last_issue
    @last_issue ||= issues.released.last
  end

  def last_issue_id
    last_issue.id
  end
end

app/controllers/api/v1/dashboard/mailing_lists_controller.rb
module Api::V1::Dashboard
  class MailingListsController < Api::V1::Dashboard::ApplicationController
    def show
      @result = MailingLists::Find.call(options)
      respond_to_result serializer: Dashboard::MailingLists::EntitySerializer
    end

    def index
      @collection = MailingLists::ScopePolicy.new(current_user).index
      respond_with Dashboard::MailingLists::CollectionSerializer.new(@collection).serialized_json
    end

    def create
      @result = MailingLists::Create.call(options.merge(params: permit_params))
      respond_to_result serializer: Dashboard::MailingLists::EntitySerializer
    end

    def update
      @result = MailingLists::Update.call(options.merge(params: permit_params))
      binding.pry
      respond_to_result serializer: Dashboard::MailingLists::EntitySerializer
    end

    def destroy
      @result = MailingLists::Destroy.call(options)
      respond_to_result
    end

    private

    def options
      {
        id: params[:id],
        params: {},
        current_user: current_user
      }
    end

    def permit_params
      params.permit(:name, :description, :slug)
    end
  end
end

app/controllers/api/v1/mailing_lists_controller.rb
module Api::V1
  class MailingListsController < Api::V1::ApplicationController
    def show
      @result = MailingLists::Find.call(params: params)
      respond_to_result serializer: MailingLists::EntitySerializer, include: [:last_issue]
    end
  end
end

app/views/mailing_lists/_header.html.haml
= render 'partials/alerts'
.row.mt-35
  .col-md-auto.mb-35.mr-auto.mailing-list-title
    = link_to mailing_list.name.humanize, mailing_list
  .col-md-auto.mb-35
    .row.align-items-center
      .col= active_link_to t('header.archives'), mailing_list_issues_path(mailing_list), class: 'header-link', active: 'active'
      - if mailing_list.last_issue
        .col= active_link_to t('header.latest'), issue_path(mailing_list.last_issue), class: 'header-link', active: 'active'
      .col= active_link_to t('header.rss'), mailing_list_issues_path(mailing_list, format: :rss), class: 'header-link', active: 'active'
      .col= link_to t('subscribe'), mailing_list, class: 'btn btn-blue-gradient'

app/views/mailing_lists/_subscribe_form.html.haml
.flex-wrap
  = simple_form_for [mailing_list, subscription], html: { class: 'inline' } do |field|
    .mr-20.grow-1= field.input :email, autofocus: local_assigns[:autofocus], label: false
    = field.button :submit, t('subscribe'), class: 'btn btn-blue-gradient'

    = yield if block_given?

app/views/mailing_lists/show.html.haml
.max-container
  .row
    .col.flash-item__wrap
      = render 'partials/alerts'
  .row.full-height
    .col-lg-6.subscribe__mailing-list
      .container
        %h1.mt-65.center.mb-35.title
          = link_to @mailing_list.name.humanize, @mailing_list
        %h2.mb-35.center.subtitle= @mailing_list.description.titleize
        .mb-25
          = render 'subscribe_form', mailing_list: @mailing_list, subscription: @subscription, autofocus: true
        - if @issue
          .description.font-16.mt-20.mb-25.center
            = t('.check_latest', href: issue_release_path(@issue)).html_safe
        - if @mailing_list.issues.count > 1
          .bottom.font-16.center
            = link_to "← #{t('header.archives')}", mailing_list_issues_path(@mailing_list), class: 'btn'

    .col-lg-6.middle-align.justify-content-center.center{ style: "background: -webkit-gradient(linear, left top, left bottom, from(#2898fb), to(#0171fd)) !important; background: linear-gradient(#2898fb, #0171fd) !important;" }
      = render layout: "layouts/iphone" do
        - if @issue
          = render 'issues/issue', mailing_list: @mailing_list, issue: @issue